### ISSUE TITLE
How to specify an upper directory that already exists...

### ISSUE THREAD

**Issue by hippyau** [mildred/ovroot#1]
Hi there!
 Nice tool :)

I'm on an embedded device, and trying to use an existing chroot made with debootstrap as the upper fs,  the goal being using the host devices root fs as lower, and debootstrap as upper.

my existing debootstrap older is /data/existing

in /data, I  `ovroot -u existing test1`

this produces the following directories in test1
```
existing/
merged/
root/
work/
```
How can I use and existing 'existing' and not make a new upper?

Cheers,

**Comment by mildred** [comment]
Hello,

ovroot is not really maintained, and it's more a proof of concept. If you want to use it for your purpose, you might need to adapt it yourself.

It uses overlayfs to layer a writable layer on top of a read only root. For that it needs a `work/` tree and a `merged/` tree on the same filesystem. The `merged/` tree contains the overlay merged filesystem and is only accessible to process created by ovroot. You cannot access it outside (or if you can, it was not designed to)

In you case, you cannot make the overlayfs mount to `/data/existing` because this is already your root. It would not be wise to mount your overlayfs on top of your root filesystem.

However, process execed by ovroot should access the overlay filesystem as its own filesystem root.

Or perhaps I did not understand your issue here.

**Comment by hippyau** [comment]
Thanks very much for your reply, and I understand you are not maintaining it.
I do have it working great though, and it's almost perfect :)
I just moved into my existing chroot into the upper, and that will be fine :)

I am however struggling badly to get the host `/tmp` as required for dbus 
I have many things working, but cannot make it work?

`mount -o bind /tmp /data/stage/hipovroot/upper/tmp` from outside and the host /tmp is not there?

I can't really follow what this line is doing  `snprintf(tmpdir_template, PATH_MAX, "%s/ovroot.%d.XXXXXX", sys_tmpdir ? sys_tmpdir : "/tmp", getpid());`

Many thanks,  hope you are safe over there!

**Comment by mildred** [comment]
Glad to know it's working for you.

However, ovroot is using mount namespaces, so I don't think you can just 
bind mount to the upper and it will work. You can probably however mount 
anything you want over ROOT before you start ovroot. And perhaps even 
after as mounts are going to be propagated.
>
> I can't really follow what this line is doing 
> |snprintf(tmpdir_template, PATH_MAX, "%s/ovroot.%d.XXXXXX", sys_tmpdir 
> ? sys_tmpdir : "/tmp", getpid());|||
>
It creates a temp directory template suitable for mkdtemp (see man 
page). This temp dir is a place where the overlay dirs are bind mounted 
prior to chroot. This tempdir location is necessary in case ROOT=/ 
because there are resistivity issues. For your setup you probably don't 
need it.
>
> Many thanks, hope you are safe over there!
>
Thank you, you too. As for COVID19, I think it's best not to worry too 
much about the illness itself. Here in France we are forced to keep at 
home for less and less good reasons. I much more fear the economic 
collapse that could follow. Stay prepared.

**Comment by hippyau** [comment]
Okay, cool!  Thanks so much for your guidance and cool little tool!
